---
title: "manny's formula"
output: html_document
date: "2024-06-12"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("~/Documents/RStudio/netdocs")

# tidyverse lets me use various "clean" syntax operators and functions!
# install.packages("tidyverse")
library(tidyverse)

# readxl lets me import excel data into the code
# install.packages("readxl")
library(readxl)

# rlang lets me detect strings
# install.packages(rlang)
library(rlang)

# data <- read_excel("Litigation Documents Sample.xlsx")
# data <- read_excel("Litigation Documents As of 6-5-24, normal version.xlsx")
sheet <- read_excel("Litigation Documents As of 6-12-24.xlsx")

matters <- unique(sheet$`@Matter - LIT`)
nonlit <- matters[470:length(matters)]

cinv <- sheet %>% 
  filter(!`@Matter - LIT` %in% nonlit) %>%
  select(id = NDDOCID,
         comment = `@Comments`,
         name,
         old = `@Document Type - LIT`)
```

```{r making keywords table}

# list of document types (ordered by hierarchy)
doctypes <- c("Docket",
              "Case Opening Documents",
              "Experts",
              "Requests for Admission",
              "Requests for Information",
              "Interrogatories",
              "Trial/Hearings",
              "Depositions",
              "Initial Disclosures",
              "Requests for Production",
              "Document Production & Review",
              "Appellate Brief & Oral Arguments",
              "Clients",
              "Settlement/Mediation",
              "Vendors/Consultants",
              "Legal Research & Memoranda",
              "Factual Research",
              "Motions, Briefs, & Arguments (non-appellate)",
              "Correspondence, Emails",
              "Communication Strategy")

# establish keywords for each doctype (ordered by hierarchy)
k_docket <- list("docket", "court doc", "ecfx")
k_cod <- list("attorney admission", "notice of admission", "noa" , "j-memo", 
           "contact", "common interest", "counsel agreement", "phv", 
           "pro hac vice", "cgs", "attorney registration", "appear",
           "atty registration", "ecf registration", "e-noticing", "e-filing", 
           "pacer link", "counsel agreement", "case opening document")
k_appellate <- list("scotus", "merits br", "cert petition", "appellate", 
                 "th cir", "st cir", "nd cir", "rd cir", "circuit", 
                 "appeal", "stay pending appeal", "en banc",  "oral arg", 
                 "1ca", "2ca", "3ca", "4ca", "5ca", "6ca", "7ca",  
                 "8ca", "9ca", "10ca", "11ca", "dcca", "fcca",
                 "ca1", "ca2", "ca3", "ca4", "ca5", "ca6", "ca7", 
                 "ca8", "ca9", "ca10", "ca11", "cadc", "cafc")
k_mba <- list("motion", "discovery mot", "to dismiss", "summary judgement", 
              "in limine", "daubert", "unitary status", "argument", "moot", 
              "prelim", "injunction", "class cert", "intervention", "amicus", 
              "amend", "compel", "mtc", "response br", "reply br", "complaint",
              "in opp", "in supp", "opp to", "supp to", "opp. to", "supp. to", 
              "mot.", "to file", "to dismiss", "mtd", "withdraw", "brief")
k_rfa <- list("request for admission", "requests for admission", "rfa")
k_rfp <- list("request for production", "requests for production", "rfp", "r4p")
k_rfi <- list("request for information", "requests for information", "rfi",
           "info req")
k_interro <- list("interrogatory", "interrogatories")
k_depo <- list("deposition subpoena", "deposition notice", "errata", 
               "deposition", "digest", "deposition outline", "deposition note",
               "depo")
k_docprod <- list("production", "privilege", "privilege log", "review protocol", 
               "production tracker", "hot doc", "discovery request", 
               "discovery resp", "district report", "review", "prod", "foia")
k_idisc <- list("disclosure")
k_setmed <- list("settlement", "offer", "mediation")
k_corr <- list("correspondence", "email", "letter", "ltr")
k_lrmemo <- list("legal research", "analysis", "memo") 
k_factr <- list("fact", "site", "map", "census", "interview", "scholarly", 
             "private investigator", "academic", "data", "photo", "research",
             "tracker")
k_experts <- list("expert")
k_clients <- list("flyer", "client engagement", "brochure", "client contacts", 
               "client retainer", "plaintiff search", 
               "litigation hold", "from client", "client")
k_vendors <- list("invoice", "contract", "vendor", "consultant", "receipt", 
                  "payment")
k_comms <- list("press", "release", "talking point", "news", "press conference", 
             "media", "communications", "comms")
k_trial <- list("trial",  "hearing", "demonstrative", "witness list", "fof", 
             "findings of fact", "conclusions of law", "direct", "cross", 
             "examination", "prep")

# if only true keyword in mba is drafts, then don't break and search for 

# make a column of lists
k_vector <- as.vector(list(k_docket, 
                           k_cod, 
                           k_experts, 
                           k_rfa, 
                           k_rfi, 
                           k_interro,
                           k_trial, 
                           k_depo, 
                           k_idisc, 
                           k_rfp, 
                           k_docprod, 
                           k_appellate,
                           k_clients, 
                           k_setmed,
                           k_vendors, 
                           k_lrmemo, 
                           k_factr, 
                           k_mba, 
                           k_corr, 
                           k_comms))

# put the doctypes and keywords together in one table, making them attributable to each other by row
kw <- data.frame(doctypes)
kw$keywords <- k_vector

# clean the environment of unneeded data products
rm(doctypes, k_vector, k_docket, k_cod, k_appellate, k_mba, k_rfa, k_rfp, k_rfi, k_interro, k_depo, k_docprod, k_idisc, k_setmed, k_corr, k_lrmemo, k_factr, k_experts, k_clients, k_vendors, k_comms, k_trial)
```

```{r search ifs}

# measure run time
start <- Sys.time()

# make blank column (container to be populated by for loop)
doctype <- c(rep(NA, nrow(cinv)))

# search, for every row in cinv (every file in netdocs)...
for(i in 1:nrow(cinv)) {
  
  profiled <- FALSE
  
  # ... for every doctype...
  for (j in 1:nrow(kw)) {
    
    # ... and compare the keywords of current doctype to row, using
    # a function that detects any selection of substrings in a primary string
    tf <- str_detect( 
      
      # content of the row as one string
      paste(cinv[i,], collapse = " "), 
      
      # look for a match with a keyword of the current doctype
      regex(as.character(unlist(kw[j, -1])),
            
            # make search case-insensitive
            ignore_case = TRUE)) 
    
    # for every keyword...
    for (k in 1:length(tf)) {
      
      # ... if a keyword is contained in the row...
      if (tf[k]) { 
        
        # ... then take the doctype corresponding to the keyword and
        # use the export container to store that categorization.
        
        doctype[i] <- kw[j, 1]
        
        # tell code this file has been successfully profiled
        profiled <- TRUE
        
        # exit the match check 
        break
        
      }
      
      # if successfully profiled, exit the keyword loop
      if (profiled) break
      
      # else, move on to the next keyword
      else next
      
    }
    
    # if successfully profiled, exit the doctype loop
    if (profiled) break
    
    # else, move on to the next doctype
    else next
    
  }
  
  # check each profiled row in cinv for doctype "na"
  if (is.na(doctype[i])) {
    
    # check the old doctype for "legacy"
    if (str_detect(paste(cinv$old[i]), "LEGACY")) {
      
      # change doctype to flag legacy
      doctype[i] <- "Legacy"
      
    }
    
    else {
      
      # change doctype to flag orphan
      doctype[i] <- "No Doctype"
      
    }
    
  }
  
}

# measure run time
end <- Sys.time()
runtime <- round(end - start, 2)

runtime
sum(doctype == "Legacy")
sum(doctype == "No Doctype")

cinv$doctype <- doctype
```

```{r check cinv}

# check for specific keywords
# data.frame(as.character(unlist(kw[j, -1])), tf) %>% 
#   filter(tf == T) %>% 
#   select(-tf) %>% 
#   array(.)

# check for top frequency keywords
# manual <- data %>% 
#   filter(doctype %in% c("Legacy", "No Doctype"))
# 
# split <- strsplit(c(manual$comment, manual$name), "[[:punct:][:space:]]+") %>% 
#   unlist() %>% 
#   as.vector(.)
# 
# analysis <- as.data.frame(split) %>% 
#   group_by(tolower(split)) %>% 
#   summarize(count = n()) %>% 
#   arrange(desc(count))
# 
# # manually slice top 10 keywords
# analysis[c(9, # discovery
#            20, # report
#            22, # images
#            28, # prep
#            29, # fact
#            49, # reports
#            73, # ediscovery
#            80, # draft
#            89, # pleadings
#            111, # drafts
#            118, # order
#            126, # exhibit
#            129 # complaint
#            ),]
```

```{r non-cinv}

# filter for non-cinv matters and pull old doctypes by id
sdoctype <- sheet %>% 
  filter(`@Matter - LIT` %in% nonlit) %>% 
  select(id = NDDOCID,
         doctype = `@Document Type - LIT`)

```


```{r export}

# combine
all <- cinv %>% 
  select(id, doctype) %>% 
  rbind(sdoctype)

# export data
write_csv(cinv, "cinvdoctypes.csv")
write_csv(all, "alldoctypes.csv")
```

